apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: frontend
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: frontend
        version: v1
    spec:
      containers:
      - name: frontend
        image: abdennebi/frontend:1.0.0-SNAPSHOT
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 80
        env:
        - name: PRODUCT_URL
          value: "http://product-service"
        - name: STOCK_URL
          value: "http://stock-service"
        - name: PORT
          value: "80"