apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
        app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: frontend
        image: abdennebi/frontend:1.0.0-SNAPSHOT
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 80
        env:
        - name: PRODUCT_URL
          value: "http://product"
        - name: STOCK_URL
          value: "http://stock"
        - name: PORT
          value: "80"
        livenessProbe:
          httpGet:
            path: /health
            port: 80
          initialDelaySeconds: 60
          periodSeconds: 10 # default is 10s
        readinessProbe:
          httpGet:
            path: /health
            port: 80
          initialDelaySeconds: 5
